#!/bin/sh

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$POSTGRES_APP_USER" WITH PASSWORD '$POSTGRES_APP_USER_PASS';
    CREATE SCHEMA "$POSTGRES_APP_SCHEMA" AUTHORIZATION "$POSTGRES_APP_USER";
    GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO "$POSTGRES_APP_USER";
    GRANT ALL ON SCHEMA public TO "$POSTGRES_APP_USER";
EOSQL
