services:
  api:
    build:
      context: ./backend
      target: base
      args:
        - VERSION=${VERSION}
    command: sh -c "python3 -m pip install --prefix=/usr/local -e . && exec uvicorn --host 0.0.0.0 --port 8000 mousse_api:app --reload"
    working_dir: /usr/local/api/
    volumes:
      - ./backend:/usr/local/api/

  frontend:
    image: node:22.3-alpine3.20
    ports:
      - 3000:8000
    working_dir: /srv/app
    volumes:
      - ./frontend:/srv/app
    environment:
      - VITE_BACKEND_HOST_URL=http://localhost:${API_PORT}
    command: >
      /bin/sh -c '
        yarn
        yarn run dev
      '
