volumes:
  postgres_data:

services:
  triton:
    restart: unless-stopped
    build:
      context: ./triton
    volumes:
      - ./triton/model-repository:/models
      - ./triton/engines:/engines
    command: [
      "tritonserver",
      "--model-repository=/models",
    ]
    ports:
      - "8880:8000" # HTTP port
      - "8881:8001" # gRPC port
      - "8882:8002" # Metrics port
    environment:
      MAX_LENGTH: ${MAX_LENGTH}
      TASK_DESCRIPTION: ${TASK_DESCRIPTION}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v2/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  tgi:
    restart: unless-stopped
    image: ghcr.io/huggingface/text-generation-inference:2.4.1
    ports:
      - 8883:80
    environment:
      - QUANTIZE=eetq
      - MODEL_ID=${LLM_MODEL}
    volumes:
      - ./tgi/model:/data
    shm_size: 2gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 100

  api:
    restart: unless-stopped
    depends_on:
      triton:
        condition: service_healthy
      tgi:
        condition: service_healthy
    image: "mousse/search-service:${VERSION}"
    build:
      context: ./backend
      target: production
      args:
        VERSION: "${VERSION}"
    ports:
      - "${API_PORT}:8000"
    environment:
      - ROOT_PATH=${ROOT_PATH:-}
      - DB_URI=postgresql+asyncpg://${POSTGRES_APP_USER}:${POSTGRES_APP_USER_PASS}@db:5432/${POSTGRES_DB}
- TRITON_URL=triton
      - TRITON_GRPC_PORT=8881
      - TRITON_MODEL_NAME=${INFERENCE_MODEL_NAME}
    volumes:
      - ./data:/var/local/data:ro
      - ./model-repository:/var/local/models:ro

  db:
    image: "mousse/postgres:16.4-postgis-pgvector"
    build:
      context: ./postgresql
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_APP_USER: ${POSTGRES_APP_USER}
      POSTGRES_APP_USER_PASS: ${POSTGRES_APP_USER_PASS}
      POSTGRES_APP_SCHEMA: core
      RUN_AS_ROOT: false
    healthcheck:
      test: "PGPASSWORD=${POSTGRES_PASSWORD} pg_isready -h 127.0.0.1 -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB}"
