"""Record Time Range Table

Revision ID: 0d4148c60875
Revises: 4ec58be5fd24
Create Date: 2024-09-11 10:31:20.940398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d4148c60875'
down_revision = '4ec58be5fd24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_time_range',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_uuid', sa.UUID(), nullable=False),
    sa.Column('time_interval', postgresql.TSTZRANGE(), nullable=False),
    sa.ForeignKeyConstraint(['record_uuid'], ['core.record.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('ix_record_time_range_time_interval', 'record_time_range', ['time_interval'], unique=False, schema='core', postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_record_time_range_time_interval', table_name='record_time_range', schema='core', postgresql_using='gist')
    op.drop_table('record_time_range', schema='core')
    # ### end Alembic commands ###
