"""Raw Record Table

Revision ID: 2a97de815307
Revises: 6afe46159f10
Create Date: 2024-09-11 10:33:21.460928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a97de815307'
down_revision = '6afe46159f10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_uuid', sa.UUID(), nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['record_uuid'], ['core.record.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('ix_raw_record_record_uuid', 'raw_record', ['record_uuid'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raw_record_record_uuid', table_name='raw_record', schema='core')
    op.drop_table('raw_record', schema='core')
    # ### end Alembic commands ###
