"""Record Table

Revision ID: 4ec58be5fd24
Revises: 
Create Date: 2024-09-11 10:29:27.853472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ec58be5fd24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('simple', 'composed', name='record_type_enum', schema='core').create(op.get_bind())
    op.create_table('record',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('geoss_id', sa.VARCHAR(length=1023), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('format', postgresql.ARRAY(sa.VARCHAR(length=1023)), nullable=True),
    sa.Column('type', postgresql.ENUM('simple', 'composed', name='record_type_enum', schema='core', create_type=False), nullable=True),
    sa.Column('keyword', postgresql.ARRAY(sa.VARCHAR(length=1023)), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    schema='core'
    )
    op.create_index('ix_record_format', 'record', ['format'], unique=False, schema='core', postgresql_using='gin')
    op.create_index('ix_record_geoss_id', 'record', ['geoss_id'], unique=False, schema='core')
    op.create_index('ix_record_keyword', 'record', ['keyword'], unique=False, schema='core', postgresql_using='gin')
    op.create_index('ix_record_type', 'record', ['type'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_record_type', table_name='record', schema='core')
    op.drop_index('ix_record_keyword', table_name='record', schema='core', postgresql_using='gin')
    op.drop_index('ix_record_geoss_id', table_name='record', schema='core')
    op.drop_index('ix_record_format', table_name='record', schema='core', postgresql_using='gin')
    op.drop_table('record', schema='core')
    sa.Enum('simple', 'composed', name='record_type_enum', schema='core').drop(op.get_bind())
    # ### end Alembic commands ###
