"""Record Topic Table

Revision ID: 6afe46159f10
Revises: 60fada80b3f3
Create Date: 2024-09-11 10:32:31.757888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6afe46159f10'
down_revision = '60fada80b3f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_topic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_uuid', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['record_uuid'], ['core.record.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['core.topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('ix_record_topic_record_uuid', 'record_topic', ['record_uuid'], unique=False, schema='core')
    op.create_index('ix_record_topic_record_uuid_topic_id', 'record_topic', ['record_uuid', 'topic_id'], unique=True, schema='core')
    op.create_index('ix_record_topic_topic_id', 'record_topic', ['topic_id'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_record_topic_topic_id', table_name='record_topic', schema='core')
    op.drop_index('ix_record_topic_record_uuid_topic_id', table_name='record_topic', schema='core')
    op.drop_index('ix_record_topic_record_uuid', table_name='record_topic', schema='core')
    op.drop_table('record_topic', schema='core')
    # ### end Alembic commands ###
