"""Countries table

Revision ID: 7078edb3ee3d
Revises: c6dc6869e83e
Create Date: 2024-11-19 10:14:58.433030

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import json

# revision identifiers, used by Alembic.
revision = '7078edb3ee3d'
down_revision = 'c6dc6869e83e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=3), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, spatial_index=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('idx_countries_code', 'countries', ['code'], unique=True, schema='core')
    op.create_index('idx_countries_geometry', 'countries', ['geometry'], unique=False, schema='core', postgresql_using='gist')
    # ### end Alembic commands ###

    with open('/var/local/data/CNTR_RG_01M_2024_4326.geojson', 'r') as f:
        data = json.load(f)['features']
    conn = op.get_bind()
    stmt = sa.text("""
        INSERT INTO core.countries (code, label, geometry)
        VALUES (:code, :label, ST_SetSRID(ST_GeomFromGeoJSON(:geometry), 4326))
    """)
    for feature in data:
        conn.execute(stmt.bindparams(code=feature['properties']['CNTR_ID'], label=feature['properties']['NAME_ENGL'], geometry=json.dumps(feature['geometry'])))

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_countries_geometry', table_name='countries', schema='core', postgresql_using='gist')
    op.drop_index('idx_countries_code', table_name='countries', schema='core')
    op.drop_table('countries', schema='core')
    # ### end Alembic commands ###
