"""Change embedding dimension

Revision ID: b96c4682f12c
Revises: 7078edb3ee3d
Create Date: 2024-11-30 09:15:58.678359

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy.vector import VECTOR


# revision identifiers, used by Alembic.
revision = 'b96c4682f12c'
down_revision = '7078edb3ee3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('embedding', 'vector',
               existing_type=VECTOR(dim=768),
               type_=VECTOR(dim=1536),
               existing_nullable=False,
               schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('embedding', 'vector',
               existing_type=VECTOR(dim=1536),
               type_=VECTOR(dim=768),
               existing_nullable=False,
               schema='core')
    # ### end Alembic commands ###
