"""Location Table

Revision ID: c0372cae9393
Revises: 2a97de815307
Create Date: 2024-09-11 10:43:51.974128

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2.types import Geometry

# revision identifiers, used by Alembic.
revision = 'c0372cae9393'
down_revision = '2a97de815307'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_uuid', sa.UUID(), nullable=False),
    sa.Column('geometry', Geometry(srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.ForeignKeyConstraint(['record_uuid'], ['core.record.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('ix_location_geometry', 'location', ['geometry'], unique=False, schema='core', postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_location_geometry', table_name='location', schema='core', postgresql_using='gist')
    op.drop_table('location', schema='core')
    # ### end Alembic commands ###
