"""Embedding Table

Revision ID: c6dc6869e83e
Revises: c0372cae9393
Create Date: 2024-09-11 10:44:55.770470

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy.vector import VECTOR

# revision identifiers, used by Alembic.
revision = 'c6dc6869e83e'
down_revision = 'c0372cae9393'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_uuid', sa.UUID(), nullable=False),
    sa.Column('vector', VECTOR(dim=768), nullable=False),
    sa.ForeignKeyConstraint(['record_uuid'], ['core.record.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('idx_vector_diskann', 'embedding', ['vector'], unique=False, schema='core', postgresql_using='diskann', postgresql_with={'storage_layout': 'plain', 'search_list_size': 200, 'num_neighbors': 20})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vector_diskann', table_name='embedding', schema='core', postgresql_using='diskann', postgresql_with={'storage_layout': 'plain', 'search_list_size': 200, 'num_neighbors': 20})
    op.drop_table('embedding', schema='core')
    # ### end Alembic commands ###
